### ISSUE TITLE
Warning: Unsafe access to vectors

### ISSUE THREAD

**Issue by nerudaj** [Hapaxia/SfmlTextAline#2]
https://github.com/Hapaxia/SfmlTextAline/blob/a5a316470b48e034ee2baa584d2b65e35b1c6cd8/SfmlTextAline/SfmlTextAline.cpp#L169

The API should provide some `getLineCount()` so the programmer can check whether they are trying to access a valid line.

Also it is symptomatic to C++ APIs to do unchecked accesses to arrays in the name of "speed", making it harder to write safe programs. Consider using `at()` method when accessing arrays, it does the boundary check and throws an exception if the index is out of bounds. If you wish, you could then do also unchecked versions of each method (like `SetLineAlignmentUnsafe` which can be clearly marked as noexcept that would keep using the `operator[]`).

It might sound like a nitpick, but realistically, who is going to change line alignment sixty times per second all of the time vs the number of people who will forget to check whether they are using a valid index?

**Comment by Hapaxia** [comment]
This is all very important stuff to know for sure, thanks indeed, but it's worth noting that m_lineAlignments is not a vector - it's an unordered_map - so if it doesn't exist, it will create it. This choice was so that you don't have to set alignments for all lines and also for the reason you mention: it could be unsafe if it didn't exist. This way, you can technically safely set the alignment for a line that doesn't exist and it'll still be there when that line does exist (unless you remove it, of course).

**Comment by nerudaj** [comment]
Oh, my bad! I so much expected it to be implemented as a vector I didn't even check...

It is up for discussion whether it makes sense that allows you to do something, without it having any observable effect (configuring a line that doesn't exist). I would still like to have a `getLineCount()` method as I can see it being handy for animation purposes (e.g.: animating line offsets so you get a wave effect).

**Comment by Hapaxia** [comment]
With the ability to move each line independently in _any_ direction (x and y), it allows a single text object to be used to display similar text in **multiple locations**. Allowing lines to be customised in advance of them existing allows certain lines to be assigned certain positions for when they are used.
Thinking about this a bit more, however, I've realised that positioning in this way (using offsets) may be difficult if anything changes the line height so an ability for absolute positioning might be more useful or maybe just the line height so it can be taken into account during offset positioning.

Retrieving useful information about the current state is always a good thing to have and the number of lines is useful information indeed so that is a good idea. I haven't yet added much in the way of getters so it could be added at around the same time that part gets fleshed out!
For now, I guess, you could pre-process a text string and count the number of `\n` it has, purposefully make a certain number of lines when designing the string, or just align more lines than you need to and it'll ignore ones that don't exist :)

**Comment by nerudaj** [comment]
I'd argue it is more important to keep the offsets over positioning each line to certain [x, y] coordinate. If I wanted to position a similar text in multiple locations, I'd simply setup a single object and then rendered it repeatedly at multiple locations.

Your class has (to me) more value if I wanted to use it to render a block of text, offseting the first line of a paragraph, etc. That is just my preference, it would be interesting to hear more opinions from hypotetical users of your class.

**Comment by Hapaxia** [comment]
I agree with you and, after having more thoughts about it, I think offsets are the best option since absolute values can be calculated if required. Using the class in this way is not the intended point of it as it's designed to help align blocks of text (as you mentioned) but, if required, it can be used to render multiple text objects in one draw call with a few positional calculations.

**Comment by Hapaxia** [comment]
Closing due to not an issue (vectors not being used and not unsafe access).

Also, added getter for number of lines.

Of course, feel free to open a new issue if you have any other problems or you can contact me elsewhere :)
