### ISSUE TITLE
Suggestion: Naming

### ISSUE THREAD

**Issue by nerudaj** [Hapaxia/SfmlTextAline#3]
Hey there! I like your project, multiline texts are cool and there are many interesting features that could be added (like formatting a single line text into multiple lines within a given frame). I could even help you with that (for example CI and packaging, I have some experience, you can look at `https://github/nerudaj/dgm-lib`.

Anyways, I have some usability suggestions with regards to naming. `SfmlTextAline` is a horrible name to type in the editor and it doesn't really capture what the class is doing. Calling it simply `MultilineText` would make it much clearer. Also, it would help immensely if the class was in its own namespace `sfmt` for example, standing for "Sfml Multiline Text".

Having your own namespace would allow you to extract the `LineAlignment` enum from the `SfmlTextAline` class, so the users don't have to type `SfmlTextAline::LineAlignment::Left` all of the time (or create extra `using` directives).

It's just a suggestion, however I think it would go a long way in improving user experience with your library (and it would allow extra classes with interesting behaviour in the future).

**Comment by Hapaxia** [comment]
Thank you for your comments and suggestions. I will be taking them into consideration.

I do usually make stuff in their own namespace, to be fair. This was supposed to be a quick replacement for SFML's Text in cases that needed aligned lines. That, too, is the reason behind the name but was given when I only intended to make it simply just alignable per object - not per line and hadn't yet considered how much customisation I was going to end up giving to each line.

As a current workaround, you can, of course, precede using the class with something like:
`using Aline = SfmlTextAline;`
and then use just **Aline** instead of the full name.

**Comment by nerudaj** [comment]
Indeed, I can shim the namespaces like this:

```cpp
namespace sfmt
{
#include "SfmlTextAline.hpp"

	using LineAlignment = SfmlTextAline::LineAlignment;
	using MultilineText = SfmlTextAline;
}
```

I only learned today I can `#include` inside a namespace to lock the included types inside that namespace 😉

**Comment by Hapaxia** [comment]
As per the recent update - [fb9039e](https://github.com/Hapaxia/SfmlTextAline/commit/fb9039eae4697685ee2a25c170a57d35bddb96f2) - some renaming and shortcutting has been applied.

The class now has a shortcut name automatically: Aline. The full name can still be used but the shortcut name is easier :)

The enum class inside the Aline class is now named just Align instead of LineAlignment.

Full access to the enum class is now simply `Aline::Align::Center`.

Hope this is more readable way to use it.  
It doesn't have its own namespace but, as you mentioned, if you need one for it, you can simply drop it into one ;)

If you still have issues, let me know.

**Comment by nerudaj** [comment]
You could've kept the `LineAlignment` or shorten it to `Alignment`. `Align` is a verb, `Alignment` is a noun. Class, enum and attribute names should be nouns. Methods and functions should be verbs.

Speaking of which, what does `Aline` stand for exactly? Is it a shorthand for "Aligned Lines"? I am thinking about it for past two days 😃

**Comment by Hapaxia** [comment]
After shortening to Align, I quite like to think I want to align it to the right so Align::Right it is! :)
Of all the things that could've been wrong with the name, I didn't expect it to be because it isn't a verb. I'll certainly think on it but I'm not sure if naming should be so strict.

Aline is basically just Align Line together, yes! Mainly because its main design is to separate the lines to be able to align them. Or, if you'd prefer it's like A-line but it doesn't really make the shape of an A...

**Comment by nerudaj** [comment]
The naming thing is sort of a convention coined by Uncle Bob Martin in his Clean Code book. The motivation is to follow natural language pattern of subject-verb-object.

Such as:

```cpp
Wheelbarrow wheelbarrow;
Person peter;
peter.push(wheelbarrow)
```

So by this logic:

```cpp
Aline multilineText;
multilineText.setAlignment(Alignment::Right); // Hey multilineText! Set the alignment to right alignment!
```

Of course, this is your project so you do you 😉 I am simply a big proponent of clean code, thus my suggestions.

**Comment by Hapaxia** [comment]
I see and that does make sense. I think the reason that I find Align so comfortable in this case is because we still commonly see "align" used as a name of a property. CSS is a common example: where you change the text-align property. It doesn't mean that right but this particular case seems quite common.

That said, it's still in version 0 (WIP) so it can still change.

I really appreciate your input. Thank you for spending time to try it out and to explain your points :)

**Comment by nerudaj** [comment]
Yeah, standard libraries in most programming languages do not adhere to clean code, they are more interested in making their names as short as possible, even if readability is somewhat impacted.

I respect your decision, as you say, things tend to evolve over time :) I think you can close this issue.

**Comment by Hapaxia** [comment]
Oops. Forgot about closing it :)

Thanks again. I mean, my first instinct was to use "alignment" so who knows? :D

**Comment by Hapaxia** [comment]
Adding an supplementary comment here to mention that the naming has been reverted back from Align to Alignment.
