### ISSUE TITLE
Round vertex coordinates on Center

### ISSUE THREAD

**Issue by xparq** [Hapaxia/SfmlTextAline#7]
Non-integer drawing coordinates cause unwanted softening (even with anti-aliasing set to 0) of fine structures, like thin lines, which is especially noticeable with rendering text, giving it an uneven appearance.

Without rounding:

![image](https://user-images.githubusercontent.com/698307/229356052-281567e6-b5cf-46fd-9d07-e18f2baa520e.png)

With rounding:

![image](https://user-images.githubusercontent.com/698307/229356066-4d253ef3-3608-43c4-83c8-c718d6c8abda.png)

-> xparq@a6b32d61a753770bddbb4be0c3eb0a6cd7d8c9c5

_(Other places where coordinates may also become fractional would need checking! I'm not familiar with the code yet, not sure if there's anything else.)_

**Comment by Hapaxia** [comment]
I've since given this some thought and it would be a bad choice to force character positions to be rounded to the nearest integer as not all views match a distance of 1 to 1 pixel. For example, a view may be using a ratio scale (0-1, 0-1) and this would only show one character as the next one would start at the end of the view. So, for that reason, always rounding to an integer must be dismissed.

However...
Aline could give the option to do so and, if so, allow the user to specify the value to round to (e.g. nearest 10, nearest 0.1 etc.). Or, always round but allow the user to modify the amount (defaulting to 1 for integer rounding).

Thank you for this suggestion. I had not yet done any pixel-peeping on its rendering so it's good to know what it's doing!
I presume this issue doesn't occur when aligning left? And I also presume it can occur if you set the position of the text to a non-integer position (presuming 1-to-1 pixel mapping)?

**Comment by xparq** [comment]
Good point about Views -- albeit I'm not familiar enough with SFML (especially views) to fully understand how exactly that char positioning issue is really a problem -- I mean, if I understand correctly, it effectively just means zooming into pixel-level, doesn't it? 
But then how would a 0.5 position offset make any significant difference at a scaling, where the glyphs themselves are already huge?

(Actually, the problem I see with views is that they could undo the stabilizing effect of rounding -- but that could happen to anything in them, so should be a concern that belongs to applying views, not their content itself.)

I also thought about an option instead, but couldn't find where _not_ rounding would be useful, that's why I didn't mention it eventually.

Anyway, (given that it's text) the most likely scenario is using it as part of some kind of a UI (as e.g. I'm planning to), with everything likely being at "normal" sizes, so (per the general principle) at least the default behavior should support the usual pixel-perfect (font) rendering, instead of sacrificing that for unlikely edge cases.

_(Interestingly, I've seen people on the SFML forum, and even in issues, complaining about mysterious text softening ("unwanted anti-aliasing"), when I myself first faced this (with vanilla SFML) and tried to figure out what's wrong. In the end I found out the hard way, later having seen it confirmed on SO, too.)_

**Comment by Hapaxia** [comment]
I've thought some more on this and realised that I'm very likely wrong with my initial conclusion.

Co-ordinates used in the text are all _local_ co-ordinates and then the _actual_ co-ordinates would be affected by character size and scale. Each character in a font gives a value (in pixels, I believe) that should be how far to the right the next character should be. If these are all integers, there's no real reason to not round to integers. Basically, the stuff about 0-1 co-ordinate systems that I mention above would only come into affect for _global_ co-ordinates; local co-ordinate system is just that: local and separate.

So, SFML texts are already integer positions for each character but could easily be forced to work "off-pixel" and that could cause "not-pixel-perfect text rendering". This would be the case here too and it's up to the user to keep it locked to pixels if that's what they need.

Rounding to integers would be the answer then but, of course, this should be optional, even if it's on by default.

Thanks again for raising this issue. I think it's an important point to address.

**Comment by Hapaxia** [comment]
fixed in 7fda596

It adds ability to round and is on by default.
It also adds other stuff too; see commit message for details!

**Comment by xparq** [comment]
Great, thanks for the fix & the enhancements, I'll check it out as soon as I find the time.
